### ISSUE TITLE
Not generating strings.xml for french languaje

### ISSUE THREAD

**Issue by renelimonglobant** [mmomtchev/expo-android-localized-app-name#1]
I'm trying to implement this feature. I ran expo prebuild to check why I can`t change the languaje and I only get default strings.xml file in android/app/src/main/res/values/strings.xml, the file android/app/src/main/res/values-fr/strings.xml doesn't exits

I follow the instructions as suggested docs, I'm testing in emulator and physical device

```js
import withAndroidLocalizedName from '@mmomtchev/expo-android-localized-app-name';

export default {
    name: 'my app',
    locales: {
        fr: './fr.json'
    },
    ios: {
        // iOS support is built-in in expo
        infoPlist: {
            CFBundleAllowMixedLocalizations: true
        }
    },
    plugins: [
        withAndroidLocalizedName
    ]
};
```

fr.json
```json
{
    "CFBundleDisplayName": "mon app",
    "app_name": "mon app"
}
```

**Comment by mmomtchev** [comment]
I just tested on a default expo install with your `app.config.js` and, after adding the mandatory `android.package` with the bundle name, the `values-fr` was correctly generated. You must have something else in your configuration.

**Comment by renelimonglobant** [comment]
Yes, I didn't notice that something was crashing when I did the prebuild and now I see the right files. My mistake
