### ISSUE TITLE
3 Moderate Severity Dependency Vulnerabilities

### ISSUE THREAD

**Issue by znenet** [mmomtchev/expo-android-localized-app-name#5]
Hi @mmomtchev,
Thank you so much for this package! 
I noticed there are 3 moderate severity dependency vulnerabilities.
Would it be possible to address these?
Again thank you very much for providing this package, made my life so much easier :)

Here is the npm audit report:

# npm audit report

xml2js  <0.5.0
Severity: moderate
xml2js is vulnerable to prototype pollution - https://github.com/advisories/GHSA-776f-qx25-q3cc
No fix available
node_modules/@mmomtchev/expo-android-localized-app-name/node_modules/xml2js
  @expo/config-plugins  <=7.1.0
  Depends on vulnerable versions of xml2js
  node_modules/@mmomtchev/expo-android-localized-app-name/node_modules/@expo/config-plugins
  @mmomtchev/expo-android-localized-app-name  *
  Depends on vulnerable versions of @expo/config-plugins
  Depends on vulnerable versions of xml2js
  node_modules/@mmomtchev/expo-android-localized-app-name

3 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

**Comment by mmomtchev** [comment]
This app is deprecated

**Comment by znenet** [comment]
Is there an alternative or a replacement of a newer better way of doing this?

**Comment by mmomtchev** [comment]
I can't find it at the moment - but a day after I published my package, another package, which seemed to be made with the support of the expo authors was also published.

As you may have seen from my profile, I am currently in the middle of a huge judicial scandal involving an extortion by the French police, judicial officials, Google, Twitter and Facebook and people are posting simultaneous comments and issues on my projects to intimidate me. Yours is one of this.

As expo have decided to back this extortion, I don't see any reason to contribute anymore. All open source projects in which I have worked have decided to follow suit, which means that I work only on projects where my contribution is significant enough to make a useful fork.
